### ISSUE TITLE
Button today in date-picker doesn't work

### ISSUE THREAD

**Issue by ybarbaria** [vaadin/expense-manager-ng2-demo#17]
Hello, 

Your button "Today" doesn't work, what is the solution getting the now day? 

Thx

**Comment by platosha** [comment]
Hello! Well, the today button behavior could be confusing sometimes, since it doesn’t select today in the picker, but rather just scrolls the month list to the current month instead. This is a known issue, we’re working on the fix currently: https://github.com/vaadin/vaadin-date-picker/issues/170

Please file the element issues in the corresponding repositories in future. The `vaadin-date-picker` issues should go to [the vaadin-date-picker repository](https://github.com/vaadin/vaadin-date-picker/issues/new).

**Comment by ybarbaria** [comment]
Thx @platosha sorry for that !
